const data = {
  platformInfo: {
    platformSlug: "steam",
    platformUserId: null,
    platformUserHandle: "matador",
    platformUserIdentifier: "76561198157740827",
    avatarUrl:
      "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/bc/bc87eee443bbb499709f15bcac40eaadc27473c5_full.jpg",
    additionalParameters: null,
  },
  userInfo: {
    userId: null,
    isPremium: false,
    isVerified: false,
    isInfluencer: false,
    isPartner: false,
    countryCode: null,
    customAvatarUrl: null,
    customHeroUrl: null,
    socialAccounts: [],
    pageviews: 2475,
    isSuspicious: null,
  },
  metadata: {
    lastUpdated: {
      value: "2021-07-24T11:29:51.5581587+00:00",
      displayValue: "2021-07-24T11:29:51.5581587+00:00",
    },
    playerId: 256433,
    currentSeason: 17,
  },
  segments: [
    {
      type: "overview",
      attributes: {},
      metadata: { name: "Lifetime" },
      expiryDate: "0001-01-01T00:00:00+00:00",
      stats: {
        wins: {
          rank: 172,
          percentile: 99.9,
          displayName: "Wins",
          displayCategory: "Performance",
          category: "performance",
          metadata: {},
          value: 20594,
          displayValue: "20,594",
          displayType: "Number",
        },
        goals: {
          rank: 227,
          percentile: 99.9,
          displayName: "Goals",
          displayCategory: "Performance",
          category: "performance",
          metadata: {},
          value: 56762,
          displayValue: "56,762",
          displayType: "Number",
        },
        mVPs: {
          rank: 292,
          percentile: 99.9,
          displayName: "MVPs",
          displayCategory: "Performance",
          category: "performance",
          metadata: {},
          value: 8745,
          displayValue: "8,745",
          displayType: "Number",
        },
        saves: {
          rank: 101,
          percentile: 99.9,
          displayName: "Saves",
          displayCategory: "Performance",
          category: "performance",
          metadata: {},
          value: 49362,
          displayValue: "49,362",
          displayType: "Number",
        },
        assists: {
          rank: 262,
          percentile: 99.9,
          displayName: "Assists",
          displayCategory: "Performance",
          category: "performance",
          metadata: {},
          value: 20343,
          displayValue: "20,343",
          displayType: "Number",
        },
        shots: {
          rank: 135,
          percentile: 99.9,
          displayName: "Shots",
          displayCategory: "Performance",
          category: "performance",
          metadata: {},
          value: 126449,
          displayValue: "126,449",
          displayType: "Number",
        },
        goalShotRatio: {
          rank: 2605936,
          percentile: 11.0,
          displayName: "Goal Shot Ratio",
          displayCategory: "Performance",
          category: "performance",
          metadata: {},
          value: 44.8892438848864,
          displayValue: "44.9",
          displayType: "NumberPrecision1",
        },
        score: {
          rank: 6195,
          percentile: 99.8,
          displayName: "TRN Score",
          displayCategory: "General",
          category: "general",
          metadata: {},
          value: 2272573.42,
          displayValue: "2,272,573.4",
          displayType: "NumberPrecision1",
        },
        seasonRewardLevel: {
          rank: null,
          percentile: 99.8,
          displayName: "Season Reward Level",
          displayCategory: "General",
          category: "general",
          metadata: {
            iconUrl:
              "https://trackercdn.com/cdn/tracker.gg/rocket-league/ranks/s4-22.png",
            rankName: "Supersonic Legend",
          },
          value: 8,
          displayValue: "8",
          displayType: "Number",
        },
        seasonRewardWins: {
          rank: null,
          percentile: null,
          displayName: "Season Reward Wins",
          displayCategory: "General",
          category: "general",
          metadata: {},
          value: 0,
          displayValue: "0",
          displayType: "Number",
        },
        tRNRating: {
          rank: null,
          percentile: null,
          displayName: "TRN Rating",
          displayCategory: "General",
          category: "general",
          metadata: {},
          value: null,
          displayValue: null,
          displayType: "NumberPrecision1",
        },
      },
    },
    {
      type: "playlist",
      attributes: { playlistId: 0, season: 17 },
      metadata: { name: "Un-Ranked" },
      expiryDate: "0001-01-01T00:00:00+00:00",
      stats: {
        tier: {
          rank: null,
          percentile: null,
          displayName: "Matches",
          displayCategory: "General",
          category: "general",
          metadata: {
            iconUrl:
              "https://trackercdn.com/cdn/tracker.gg/rocket-league/ranks/s4-0.png",
            name: "Unranked",
          },
          value: 0,
          displayValue: "0",
          displayType: "Number",
        },
        division: {
          rank: null,
          percentile: null,
          displayName: "Matches",
          displayCategory: "General",
          category: "general",
          metadata: { name: "Division I" },
          value: 0,
          displayValue: "0",
          displayType: "Number",
        },
        matchesPlayed: {
          rank: null,
          percentile: null,
          displayName: "Matches",
          displayCategory: "Performance",
          category: "performance",
          metadata: {},
          value: 0,
          displayValue: "0",
          displayType: "Number",
        },
        winStreak: {
          rank: null,
          percentile: null,
          displayName: "WinStreak",
          displayCategory: "Performance",
          category: "performance",
          metadata: { type: "win" },
          value: 0,
          displayValue: "0",
          displayType: "Number",
        },
        rating: {
          rank: 1743701,
          percentile: 80.0,
          displayName: "Rating",
          displayCategory: "Skill",
          category: "skill",
          metadata: {},
          value: 1406,
          displayValue: "1,406",
          displayType: "Number",
        },
      },
    },
    {
      type: "playlist",
      attributes: { playlistId: 10, season: 17 },
      metadata: { name: "Ranked Duel 1v1" },
      expiryDate: "0001-01-01T00:00:00+00:00",
      stats: {
        tier: {
          rank: null,
          percentile: 99.8,
          displayName: "Matches",
          displayCategory: "General",
          category: "general",
          metadata: {
            iconUrl:
              "https://trackercdn.com/cdn/tracker.gg/rocket-league/ranks/s15rank20.png",
            name: "Grand Champion II",
          },
          value: 20,
          displayValue: "20",
          displayType: "Number",
        },
        division: {
          rank: null,
          percentile: 64.0,
          displayName: "Matches",
          displayCategory: "General",
          category: "general",
          metadata: { deltaDown: 6, deltaUp: 12, name: "Division II" },
          value: 1,
          displayValue: "1",
          displayType: "Number",
        },
        matchesPlayed: {
          rank: null,
          percentile: 97.9,
          displayName: "Matches",
          displayCategory: "Performance",
          category: "performance",
          metadata: {},
          value: 172,
          displayValue: "172",
          displayType: "Number",
        },
        winStreak: {
          rank: null,
          percentile: 9.0,
          displayName: "WinStreak",
          displayCategory: "Performance",
          category: "performance",
          metadata: { type: "loss" },
          value: 3,
          displayValue: "-3",
          displayType: "Number",
        },
        rating: {
          rank: 12911,
          percentile: 99.8,
          displayName: "Rating",
          displayCategory: "Skill",
          category: "skill",
          metadata: {},
          value: 1246,
          displayValue: "1,246",
          displayType: "Number",
        },
      },
    },
    {
      type: "playlist",
      attributes: { playlistId: 11, season: 17 },
      metadata: { name: "Ranked Doubles 2v2" },
      expiryDate: "0001-01-01T00:00:00+00:00",
      stats: {
        tier: {
          rank: null,
          percentile: 99.9,
          displayName: "Matches",
          displayCategory: "General",
          category: "general",
          metadata: {
            iconUrl:
              "https://trackercdn.com/cdn/tracker.gg/rocket-league/ranks/s15rank22.png",
            name: "Supersonic Legend",
          },
          value: 22,
          displayValue: "22",
          displayType: "Number",
        },
        division: {
          rank: null,
          percentile: null,
          displayName: "Matches",
          displayCategory: "General",
          category: "general",
          metadata: { deltaDown: 22, deltaUp: 188, name: "Division I" },
          value: 0,
          displayValue: "0",
          displayType: "Number",
        },
        matchesPlayed: {
          rank: null,
          percentile: 98.4,
          displayName: "Matches",
          displayCategory: "Performance",
          category: "performance",
          metadata: {},
          value: 652,
          displayValue: "652",
          displayType: "Number",
        },
        winStreak: {
          rank: null,
          percentile: 81.0,
          displayName: "WinStreak",
          displayCategory: "Performance",
          category: "performance",
          metadata: { type: "win" },
          value: 2,
          displayValue: "2",
          displayType: "Number",
        },
        rating: {
          rank: 2081,
          percentile: 99.9,
          displayName: "Rating",
          displayCategory: "Skill",
          category: "skill",
          metadata: {},
          value: 1884,
          displayValue: "1,884",
          displayType: "Number",
        },
      },
    },
    {
      type: "playlist",
      attributes: { playlistId: 13, season: 17 },
      metadata: { name: "Ranked Standard 3v3" },
      expiryDate: "0001-01-01T00:00:00+00:00",
      stats: {
        tier: {
          rank: null,
          percentile: 99.9,
          displayName: "Matches",
          displayCategory: "General",
          category: "general",
          metadata: {
            iconUrl:
              "https://trackercdn.com/cdn/tracker.gg/rocket-league/ranks/s15rank22.png",
            name: "Supersonic Legend",
          },
          value: 22,
          displayValue: "22",
          displayType: "Number",
        },
        division: {
          rank: null,
          percentile: null,
          displayName: "Matches",
          displayCategory: "General",
          category: "general",
          metadata: { deltaDown: 80, deltaUp: 84, name: "Division I" },
          value: 0,
          displayValue: "0",
          displayType: "Number",
        },
        matchesPlayed: {
          rank: null,
          percentile: 99.6,
          displayName: "Matches",
          displayCategory: "Performance",
          category: "performance",
          metadata: {},
          value: 844,
          displayValue: "844",
          displayType: "Number",
        },
        winStreak: {
          rank: null,
          percentile: 63.0,
          displayName: "WinStreak",
          displayCategory: "Performance",
          category: "performance",
          metadata: { type: "win" },
          value: 1,
          displayValue: "1",
          displayType: "Number",
        },
        rating: {
          rank: 1328,
          percentile: 99.9,
          displayName: "Rating",
          displayCategory: "Skill",
          category: "skill",
          metadata: {},
          value: 1941,
          displayValue: "1,941",
          displayType: "Number",
        },
      },
    },
    {
      type: "playlist",
      attributes: { playlistId: 27, season: 17 },
      metadata: { name: "Hoops" },
      expiryDate: "0001-01-01T00:00:00+00:00",
      stats: {
        tier: {
          rank: null,
          percentile: 99.9,
          displayName: "Matches",
          displayCategory: "General",
          category: "general",
          metadata: {
            iconUrl:
              "https://trackercdn.com/cdn/tracker.gg/rocket-league/ranks/s15rank20.png",
            name: "Grand Champion II",
          },
          value: 20,
          displayValue: "20",
          displayType: "Number",
        },
        division: {
          rank: null,
          percentile: 90.0,
          displayName: "Matches",
          displayCategory: "General",
          category: "general",
          metadata: { deltaDown: 1, deltaUp: 18, name: "Division III" },
          value: 2,
          displayValue: "2",
          displayType: "Number",
        },
        matchesPlayed: {
          rank: null,
          percentile: 95.9,
          displayName: "Matches",
          displayCategory: "Performance",
          category: "performance",
          metadata: {},
          value: 38,
          displayValue: "38",
          displayType: "Number",
        },
        winStreak: {
          rank: null,
          percentile: 28.0,
          displayName: "WinStreak",
          displayCategory: "Performance",
          category: "performance",
          metadata: { type: "loss" },
          value: 1,
          displayValue: "-1",
          displayType: "Number",
        },
        rating: {
          rank: 4642,
          percentile: 99.9,
          displayName: "Rating",
          displayCategory: "Skill",
          category: "skill",
          metadata: {},
          value: 1179,
          displayValue: "1,179",
          displayType: "Number",
        },
      },
    },
    {
      type: "playlist",
      attributes: { playlistId: 28, season: 17 },
      metadata: { name: "Rumble" },
      expiryDate: "0001-01-01T00:00:00+00:00",
      stats: {
        tier: {
          rank: null,
          percentile: 99.5,
          displayName: "Matches",
          displayCategory: "General",
          category: "general",
          metadata: {
            estimated: true,
            iconUrl:
              "https://trackercdn.com/cdn/tracker.gg/rocket-league/ranks/s15rank19.png",
            name: "Grand Champion I",
          },
          value: 19,
          displayValue: "19",
          displayType: "Number",
        },
        division: {
          rank: null,
          percentile: 87.0,
          displayName: "Matches",
          displayCategory: "General",
          category: "general",
          metadata: { estimated: true, name: "Division III" },
          value: 2,
          displayValue: "2",
          displayType: "Number",
        },
        matchesPlayed: {
          rank: null,
          percentile: 71.0,
          displayName: "Matches",
          displayCategory: "Performance",
          category: "performance",
          metadata: {},
          value: 8,
          displayValue: "8",
          displayType: "Number",
        },
        winStreak: {
          rank: null,
          percentile: 28.0,
          displayName: "WinStreak",
          displayCategory: "Performance",
          category: "performance",
          metadata: { type: "loss" },
          value: 1,
          displayValue: "-1",
          displayType: "Number",
        },
        rating: {
          rank: 16233,
          percentile: 99.7,
          displayName: "Rating",
          displayCategory: "Skill",
          category: "skill",
          metadata: {},
          value: 1243,
          displayValue: "1,243",
          displayType: "Number",
        },
      },
    },
    {
      type: "playlist",
      attributes: { playlistId: 29, season: 17 },
      metadata: { name: "Dropshot" },
      expiryDate: "0001-01-01T00:00:00+00:00",
      stats: {
        tier: {
          rank: null,
          percentile: 99.6,
          displayName: "Matches",
          displayCategory: "General",
          category: "general",
          metadata: {
            estimated: true,
            iconUrl:
              "https://trackercdn.com/cdn/tracker.gg/rocket-league/ranks/s4-17.png",
            name: "Champion II",
          },
          value: 17,
          displayValue: "17",
          displayType: "Number",
        },
        division: {
          rank: null,
          percentile: 97.3,
          displayName: "Matches",
          displayCategory: "General",
          category: "general",
          metadata: { estimated: true, name: "Division IV" },
          value: 3,
          displayValue: "3",
          displayType: "Number",
        },
        matchesPlayed: {
          rank: null,
          percentile: 69.0,
          displayName: "Matches",
          displayCategory: "Performance",
          category: "performance",
          metadata: {},
          value: 3,
          displayValue: "3",
          displayType: "Number",
        },
        winStreak: {
          rank: null,
          percentile: 27.0,
          displayName: "WinStreak",
          displayCategory: "Performance",
          category: "performance",
          metadata: { type: "loss" },
          value: 1,
          displayValue: "-1",
          displayType: "Number",
        },
        rating: {
          rank: 17077,
          percentile: 99.7,
          displayName: "Rating",
          displayCategory: "Skill",
          category: "skill",
          metadata: {},
          value: 1024,
          displayValue: "1,024",
          displayType: "Number",
        },
      },
    },
    {
      type: "playlist",
      attributes: { playlistId: 30, season: 17 },
      metadata: { name: "Snowday" },
      expiryDate: "0001-01-01T00:00:00+00:00",
      stats: {
        tier: {
          rank: null,
          percentile: 99.8,
          displayName: "Matches",
          displayCategory: "General",
          category: "general",
          metadata: {
            estimated: true,
            iconUrl:
              "https://trackercdn.com/cdn/tracker.gg/rocket-league/ranks/s4-18.png",
            name: "Champion III",
          },
          value: 18,
          displayValue: "18",
          displayType: "Number",
        },
        division: {
          rank: null,
          percentile: 91.0,
          displayName: "Matches",
          displayCategory: "General",
          category: "general",
          metadata: { estimated: true, name: "Division II" },
          value: 1,
          displayValue: "1",
          displayType: "Number",
        },
        matchesPlayed: {
          rank: null,
          percentile: 88.0,
          displayName: "Matches",
          displayCategory: "Performance",
          category: "performance",
          metadata: {},
          value: 8,
          displayValue: "8",
          displayType: "Number",
        },
        winStreak: {
          rank: null,
          percentile: 79.0,
          displayName: "WinStreak",
          displayCategory: "Performance",
          category: "performance",
          metadata: { type: "win" },
          value: 2,
          displayValue: "2",
          displayType: "Number",
        },
        rating: {
          rank: 15607,
          percentile: 99.7,
          displayName: "Rating",
          displayCategory: "Skill",
          category: "skill",
          metadata: {},
          value: 1042,
          displayValue: "1,042",
          displayType: "Number",
        },
      },
    },
    {
      type: "playlist",
      attributes: { playlistId: 34, season: 17 },
      metadata: { name: "Tournament Matches" },
      expiryDate: "0001-01-01T00:00:00+00:00",
      stats: {
        tier: {
          rank: null,
          percentile: 99.9,
          displayName: "Matches",
          displayCategory: "General",
          category: "general",
          metadata: {
            iconUrl:
              "https://trackercdn.com/cdn/tracker.gg/rocket-league/ranks/s15rank22.png",
            name: "Supersonic Legend",
          },
          value: 22,
          displayValue: "22",
          displayType: "Number",
        },
        division: {
          rank: null,
          percentile: null,
          displayName: "Matches",
          displayCategory: "General",
          category: "general",
          metadata: { deltaDown: 148, deltaUp: 86, name: "Division I" },
          value: 0,
          displayValue: "0",
          displayType: "Number",
        },
        matchesPlayed: {
          rank: null,
          percentile: 95.6,
          displayName: "Matches",
          displayCategory: "Performance",
          category: "performance",
          metadata: {},
          value: 126,
          displayValue: "126",
          displayType: "Number",
        },
        winStreak: {
          rank: null,
          percentile: 31.0,
          displayName: "WinStreak",
          displayCategory: "Performance",
          category: "performance",
          metadata: { type: "loss" },
          value: 1,
          displayValue: "-1",
          displayType: "Number",
        },
        rating: {
          rank: 925,
          percentile: 99.9,
          displayName: "Rating",
          displayCategory: "Skill",
          category: "skill",
          metadata: {},
          value: 2008,
          displayValue: "2,008",
          displayType: "Number",
        },
      },
    },
  ],
  availableSegments: [
    { type: "playlist", attributes: { season: 1 }, metadata: { name: "1" } },
    { type: "playlist", attributes: { season: 2 }, metadata: { name: "2" } },
    { type: "playlist", attributes: { season: 3 }, metadata: { name: "3" } },
    { type: "playlist", attributes: { season: 4 }, metadata: { name: "4" } },
    { type: "playlist", attributes: { season: 5 }, metadata: { name: "5" } },
    { type: "playlist", attributes: { season: 6 }, metadata: { name: "6" } },
    { type: "playlist", attributes: { season: 7 }, metadata: { name: "7" } },
    { type: "playlist", attributes: { season: 8 }, metadata: { name: "8" } },
    { type: "playlist", attributes: { season: 9 }, metadata: { name: "9" } },
    {
      type: "playlist",
      attributes: { season: 10 },
      metadata: { name: "10" },
    },
    {
      type: "playlist",
      attributes: { season: 11 },
      metadata: { name: "11" },
    },
    {
      type: "playlist",
      attributes: { season: 12 },
      metadata: { name: "12" },
    },
    {
      type: "playlist",
      attributes: { season: 13 },
      metadata: { name: "13" },
    },
    {
      type: "playlist",
      attributes: { season: 14 },
      metadata: { name: "14" },
    },
    {
      type: "playlist",
      attributes: { season: 15 },
      metadata: { name: "Season 1 (15)" },
    },
    {
      type: "playlist",
      attributes: { season: 16 },
      metadata: { name: "Season 2 (16)" },
    },
    {
      type: "playlist",
      attributes: { season: 17 },
      metadata: { name: "Season 3 (17)" },
    },
  ],
  expiryDate: "2021-07-24T11:35:51.624822+00:00",
};

export default data;
