module.exports = {
  PLATFORMS: ["psn", "xbl", "steam", "epic", "switch"],
  timeLeftendOfSeason: 1637161200, // Unix
  season: 4,
  siteStatus: { closed: false, title: "HELP", text: "Why bro :(" },
  seasons: [
    { name: "S4 (18)", number: 18 },
    { name: "S3 (17)", number: 17 },
    { name: "S2 (16)", number: 16 },
    { name: "S1 (15)", number: 15 },
    { name: "14", number: 14 },
    { name: "13", number: 13 },
    { name: "12", number: 12 },
    { name: "11", number: 11 },
    { name: "10", number: 10 },
    { name: "9", number: 9 },
    { name: "8", number: 8 },
    { name: "7", number: 7 },
    { name: "6", number: 6 },
    { name: "5", number: 5 },
    { name: "4", number: 4 },
    { name: "3", number: 3 },
    { name: "2", number: 2 },
    { name: "1", number: 1 },
  ],
};
