module.exports = {
  Standard: 13,
  Doubles: 11,
  Duel: 10,
  Unranked: 0,
  Rumble: 28,
  Dropshot: 29,
  Snowday: 30,
  Hoops: 27,
  Tournament: 34,
  tiers: {
    1: "Bronze I",
    2: "Bronze II",
    3: "Bronze III",
    4: "Silver I",
    5: "Silver II",
    6: "Silver III",
    7: "Gold I",
    8: "Gold II",
    9: "Gold III",
    10: "Platinum I",
    11: "Platinum II",
    12: "Platinum III",
    13: "Diamond I",
    14: "Diamond II",
    15: "Diamond III",
    16: "Champion I",
    17: "Champion II",
    18: "Champion III",
    19: "Grand Champion I",
    20: "Grand Champion II",
    21: "Grand Champion III",
    22: "Supersonic Legend",
  },
};
